"""empty message

Revision ID: 27589b923e82
Revises: 807c457490d8
Create Date: 2024-09-17 15:55:22.756957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27589b923e82'
down_revision = '807c457490d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('train', schema=None) as batch_op:
        batch_op.alter_column('times',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('train', schema=None) as batch_op:
        batch_op.alter_column('times',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    op.drop_table('users')
    # ### end Alembic commands ###
